server:
  port: 8083

spring:
  application:
    name: NotificationService
  
  # Dedicated DB for Notifications (Shares the same MySQL container on 3307)
  datasource:
    url: jdbc:mysql://localhost:3307/notificationdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka Consumer Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Service Registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/