server:
  port: 8080
  max-http-request-header-size: 32KB

spring:
  security:
    user:
      name: admin
      password: password
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        max-header-size: 32KB
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:3002"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: drop-noise
          uri: no://op
          predicates:
            # Catch stray actuator requests on port 8080 and blackhole them
            - Path=/.well-known/**, /404, /actuator/**
          filters:
            - SetStatus=404
        - id: recipe-service
          uri: lb://RECIEPE
          predicates:
            - Path=/api/recipes/**

        - id: recipe-ui
          uri: http://localhost:3001
          predicates:
            - Path=/**

        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: api-gateway