Server:
  port: 8082

spring:
  application:
    name: Reciepe
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: password


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

