services:
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: root